name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: macos-12-xl

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --release
    - name: Archive production artifacts
      uses: actions/upload-artifact@v4
      with:
        name: mealplanner_mac
        path: target/release/mealplanner
